### ISSUE TITLE
Clear cache command should also add log in sys_log when you clear Varnish cache

### ISSUE THREAD

**Issue by clement-michelet** [snowflakech/typo3-varnish#12]
Hi,

When you use the use the clear cache command, there is a log added in sys_log which indicate :
* who asked this
* what command is sent
* where it is applied

If you use the 'Clear Varnish Cache' command, no sys_log is added. It must be loggued as a backend action like the TYPO3 clear cache command (but with a different text).

Regards,
Clément

**Comment by andristeiner** [comment]
Hi Clément. From what i unserstand you refer to the "Clear Varnish Cache" within the clear cache menu (Lightning symbol), right? The action called there is tx_varnish_hooks_ajax::banAll which issues a varnishController::clearCache('all') command then. This is the very same method also used within all other commands and also where the logging occurs. Therefore, logging should take place always, regardless of the used method. If i understood something wrong, please clarify four intentions.

**Comment by clement-michelet** [comment]
Hi Andri,

Yes, I'll refer only to the menu item "Clear Varnish Cache"
The TYPO3 command for page clear cache command add a log in sys_log table :
```
14:32:56		admin@LIVE		CACHE		Clear Cache		User admin has cleared the cache (cacheCmd=pages)
```

When you ask to clear page cache with native menu command, an hook is triggered to clear varnish cache. TYPO3 add an entry in the log like above.

Currently, EXT:varnish add entries only in devLog which is already great. My feature request is to add an entry in sys_log when click on the menu item "Clear Varnish Cache" with a message like "User %1$s has cleared the cache (cacheCmd=%1$s)" with :
1. BE username
2. Command key : varnish ?

I think it should be a simple call to writelog like here : http://api.typo3.org/typo3cms/62/html/_data_handler_8php_source.html#l07139

Regards,
Clément

**Comment by andristeiner** [comment]
Ah i see. Thank you for clarifying! I will add this to the next release then, unfortunatley i just publish a release a few minutes ago.

**Comment by andristeiner** [comment]
Added to master. As written above, its not yet included in a release but available in master here. As i just published a release today i will wait a few week/months for the next one.

**Comment by clement-michelet** [comment]
Thanks a lot for your quick commit !
