### ISSUE TITLE
Support TYPO3 Context to allow specific configuration per environments

### ISSUE THREAD

**Issue by clement-michelet** [snowflakech/typo3-varnish#14]
Hi Andri,

Since 6.2 LTS version, TYPO3 supports the application contexts: development, testing, production, etc.
This feature allow to deploy on different environments with a tools like TYPO3 Surf. 
The environment specific configurations can be defined inside the file `typo3conf/AdditionalConfiguration.php`.

My proposal is to allow to override the unserialized configuration. If we have specific configuration, we should put them in `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['varnish']['my_key'] = 'my value';`.

Regards,
Clément

**Comment by andristeiner** [comment]
Hi Clément
Cool stuff, thanks a lot! I'll merge your PR into the next minor version, however as there are no other changes pending right now it could take some time.
Cheers,
Andri
