### ISSUE TITLE
Fatal Error when calling 'Clear Varnish cache' after clearing TYPO3's system cache

### ISSUE THREAD

**Issue by Sevyls** [snowflakech/typo3-varnish#16]
When a CMS admin clicks on "Clear System cache" in the backend of TYPO3 and wants to clear the Varnish cache afterwards, it results in the following Error message:
 
``Fatal error: Class 'tx_varnish_controller' not found in /var/www/project/typo3_src-6.2.14/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4433``

When I clear all caches & the php opcode cache (here: APC) in TYPO3's install tool, the "Clear Varnish cache"  works again.

Don't know if this is an extension bug or a TYPO3 core bug. 
Please assist.

**Comment by andristeiner** [comment]
Which PHP Version do you use? I cannot reproduce this behaviour here.

**Comment by julianxhokaxhiu** [comment]
Here we are using two version:
- PHP 5.5.21 [PRODUCTION]
- PHP 5.6.14-1 [DEVELOPMENT]

Happing in both the versions.

**Comment by andristeiner** [comment]
Please check with the latest master, there was a big restructure- and namespacing going on in ec0070431321a5b98fb7bea02f4225c1d47a9d3a which might resolve such problems as well

**Comment by julianxhokaxhiu** [comment]
I'll try this on monday :) thank you

**Comment by andristeiner** [comment]
If you still encounter any problems, just let me know.
