### ISSUE TITLE
TYPO3 Sitename correct?

### ISSUE THREAD

**Issue by obi12341** [snowflakech/typo3-varnish#22]
Looks like the sitename doesn't get rendered correctly. We always see something like this in the headers:
typo3-sitename:442078075901dadf4fd855cde75e62e590e5b001

Is this hash correct, or should there be something more like the real TYPO3 Sitename?

TYPO3 7.6
varnish 4

**Comment by andristeiner** [comment]
To prevent problems with special chars, encoding and so, the site name is hashed with `GeneralUtility::hmac`, so this looks fine to me.
