### ISSUE TITLE
TYPO3 8.5.* + Composer Support

### ISSUE THREAD

**Issue by steve-buri** [snowflakech/typo3-varnish#26]
Hey Andri,

is there a way to install this extention via composer? My TYPO3 is using the latest version (which is installed via composer). So the extentions need to be installed via composer, too.

Is your extention already working with TYPO3 8?

Thanks in advance

Best..
Steve

**Comment by andristeiner** [comment]
Hi Steve,

By now, there is nothing composer related in there, pull requests are welcome of course :smile: 

While i have not tested the extension with TYPO3 version 8 yet, i don't think you should face insurmountable problems. 

I'll create a updated versions with TYPO3 8 support and all pull requests included somewhen this year.

If you have any other questions, please use the TYPO3-english mailinglist or Slack.

Cheers, Andri
