### ISSUE TITLE
VCL for Varnish 4.x

### ISSUE THREAD

**Issue by neufeind** [snowflakech/typo3-varnish#9]
Only small (but important) changes are needed for a default.vcl to be used with Varnish 4.x.

Maybe consider shipping simply two files for the moment. Still Varnish 3.x has a broad userbase, but new installations meanwhile use 4.x.

**Comment by andristeiner** [comment]
Thanks to @neufeind for reporting and @jmverges for providing the updates example. Will include this in the upcoming 1.0.7 release.
